name: "Trigger database backup action on CRON schedule"
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  #runs every 5mins
  # 'min hour dayOfMonth month day'
jobs:
  restore:
    runs-on: self-hosted

    steps:
    #clones repository into the virtual machine the github code will
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MongoDB database tools
        run:
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.9.0.tgz
      - name: Extract files
        run:
          tar -xvzf mongodb-database-tools-*.tgz
      - name: make executibles global
        run:
          sudo mv mongodb-database-tools-*/bin/* /usr/local/bin/
      - name: go to root
        run: cd /
      - name: go to folder
        run: cd workspaces/testFolder
      - name: Run backup
        env:
          MONGO_URI: ${{ secrets.MONGO_URI}}
        run: 
          mongorestore --uri="$MONGO_URI" --db DeeinderBackup1 --drop dump/Deeinder
      
    
